Traceback (most recent call last):
  File "/home/yaphg/Downloads/repo03-latest/data/good-operators-unit-exp/runs-00001-00100/00001/../../goodops-parser.py", line 32, in <module>
    main()
  File "/home/yaphg/Downloads/repo03-latest/data/good-operators-unit-exp/runs-00001-00100/00001/../../goodops-parser.py", line 27, in main
    parser.parse()
  File "/home/yaphg/.local/lib/python3.10/site-packages/lab/parser.py", line 213, in parse
    with open(function.filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'good_operators'
